# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sala_juego.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_sala(object):
    def setupUi(self, sala):
        sala.setObjectName("sala")
        sala.resize(814, 600)
        sala.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        sala.setStyleSheet("background-color: rgb(63, 63, 94);")
        self.centralwidget = QtWidgets.QWidget(sala)
        self.centralwidget.setObjectName("centralwidget")
        self.jugar_poker = QtWidgets.QLabel(self.centralwidget)
        self.jugar_poker.setGeometry(QtCore.QRect(170, 0, 551, 41))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.jugar_poker.setFont(font)
        self.jugar_poker.setObjectName("jugar_poker")
        self.fondosala = QtWidgets.QLabel(self.centralwidget)
        self.fondosala.setGeometry(QtCore.QRect(20, 30, 781, 541))
        self.fondosala.setStyleSheet("border-image: url(:/mesa/mesapoker.jpg);")
        self.fondosala.setText("")
        self.fondosala.setObjectName("fondosala")
        self.Charmi = QtWidgets.QLabel(self.centralwidget)
        self.Charmi.setGeometry(QtCore.QRect(350, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Charmi.setFont(font)
        self.Charmi.setObjectName("Charmi")
        self.c1U = QtWidgets.QLabel(self.centralwidget)
        self.c1U.setGeometry(QtCore.QRect(350, 400, 51, 81))
        self.c1U.setText("")
        self.c1U.setObjectName("c1U")
        self.c2U = QtWidgets.QLabel(self.centralwidget)
        self.c2U.setGeometry(QtCore.QRect(430, 400, 51, 81))
        self.c2U.setText("")
        self.c2U.setObjectName("c2U")
        self.c1C = QtWidgets.QLabel(self.centralwidget)
        self.c1C.setGeometry(QtCore.QRect(370, 80, 41, 61))
        self.c1C.setStyleSheet("border-image: url(:/mazo/mazo.jpg);")
        self.c1C.setText("")
        self.c1C.setObjectName("c1C")
        self.c2C = QtWidgets.QLabel(self.centralwidget)
        self.c2C.setGeometry(QtCore.QRect(420, 80, 41, 61))
        self.c2C.setStyleSheet("border-image: url(:/mazo/mazo.jpg);")
        self.c2C.setText("")
        self.c2C.setObjectName("c2C")
        self.btn_pasar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pasar.setGeometry(QtCore.QRect(180, 480, 85, 27))
        self.btn_pasar.setObjectName("btn_pasar")
        self.btn_Allin = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Allin.setGeometry(QtCore.QRect(670, 480, 85, 27))
        self.btn_Allin.setObjectName("btn_Allin")
        self.btn_retirarse = QtWidgets.QPushButton(self.centralwidget)
        self.btn_retirarse.setGeometry(QtCore.QRect(50, 480, 85, 27))
        self.btn_retirarse.setObjectName("btn_retirarse")
        self.subida = QtWidgets.QSpinBox(self.centralwidget)
        self.subida.setGeometry(QtCore.QRect(540, 490, 91, 41))
        self.subida.setStyleSheet("background-color: rgb(63, 63, 94);\n"
"color: rgb(0, 0, 127);\n"
"font: 75 italic 11pt \"Noto Sans\";")
        self.subida.setObjectName("subida")
        self.btn_subir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_subir.setGeometry(QtCore.QRect(540, 460, 85, 27))
        self.btn_subir.setObjectName("btn_subir")
        self.c1M = QtWidgets.QLabel(self.centralwidget)
        self.c1M.setGeometry(QtCore.QRect(240, 230, 61, 81))
        self.c1M.setStyleSheet("")
        self.c1M.setText("")
        self.c1M.setObjectName("c1M")
        self.c2M = QtWidgets.QLabel(self.centralwidget)
        self.c2M.setGeometry(QtCore.QRect(310, 230, 61, 81))
        self.c2M.setStyleSheet("")
        self.c2M.setText("")
        self.c2M.setObjectName("c2M")
        self.c4M = QtWidgets.QLabel(self.centralwidget)
        self.c4M.setGeometry(QtCore.QRect(450, 230, 61, 81))
        self.c4M.setStyleSheet("")
        self.c4M.setText("")
        self.c4M.setObjectName("c4M")
        self.c3M = QtWidgets.QLabel(self.centralwidget)
        self.c3M.setGeometry(QtCore.QRect(380, 230, 61, 81))
        self.c3M.setStyleSheet("")
        self.c3M.setText("")
        self.c3M.setObjectName("c3M")
        self.c5M = QtWidgets.QLabel(self.centralwidget)
        self.c5M.setGeometry(QtCore.QRect(520, 230, 61, 81))
        self.c5M.setStyleSheet("")
        self.c5M.setText("")
        self.c5M.setObjectName("c5M")
        self.bienvenido = QtWidgets.QLineEdit(self.centralwidget)
        self.bienvenido.setGeometry(QtCore.QRect(530, 40, 231, 31))
        self.bienvenido.setStyleSheet("color: rgb(243, 0, 0);")
        self.bienvenido.setText("")
        self.bienvenido.setObjectName("bienvenido")
        self.user = QtWidgets.QLineEdit(self.centralwidget)
        self.user.setGeometry(QtCore.QRect(360, 490, 113, 27))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK TC")
        font.setBold(True)
        font.setWeight(75)
        self.user.setFont(font)
        self.user.setStyleSheet("color: rgb(243, 0, 0);")
        self.user.setText("")
        self.user.setObjectName("user")
        self.bote_mesa = QtWidgets.QLineEdit(self.centralwidget)
        self.bote_mesa.setGeometry(QtCore.QRect(330, 310, 161, 27))
        self.bote_mesa.setStyleSheet("color: rgb(243, 0, 0);")
        self.bote_mesa.setText("")
        self.bote_mesa.setObjectName("bote_mesa")
        self.bote_charmi = QtWidgets.QLineEdit(self.centralwidget)
        self.bote_charmi.setGeometry(QtCore.QRect(360, 150, 113, 27))
        self.bote_charmi.setStyleSheet("color: rgb(243, 0, 0);")
        self.bote_charmi.setText("")
        self.bote_charmi.setObjectName("bote_charmi")
        self.bote_user = QtWidgets.QLineEdit(self.centralwidget)
        self.bote_user.setGeometry(QtCore.QRect(360, 360, 113, 27))
        self.bote_user.setStyleSheet("color: rgb(243, 0, 0);")
        self.bote_user.setText("")
        self.bote_user.setObjectName("bote_user")
        self.resultado = QtWidgets.QLineEdit(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(270, 200, 281, 31))
        self.resultado.setStyleSheet("color: rgb(243, 0, 0);")
        self.resultado.setObjectName("resultado")
        sala.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(sala)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 27))
        self.menubar.setObjectName("menubar")
        sala.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(sala)
        self.statusbar.setObjectName("statusbar")
        sala.setStatusBar(self.statusbar)

        self.retranslateUi(sala)
        QtCore.QMetaObject.connectSlotsByName(sala)

    def retranslateUi(self, sala):
        _translate = QtCore.QCoreApplication.translate
        sala.setWindowTitle(_translate("sala", "MainWindow"))
        self.jugar_poker.setText(_translate("sala", "<html><head/><body><p align=\"center\"><span style=\" color:#ff5500; vertical-align:super;\">!Bienvenido a jugar poker con charmi¡</span></p></body></html>"))
        self.Charmi.setText(_translate("sala", "<html><head/><body><p><span style=\" color:#ff5500;\">Charmi</span></p></body></html>"))
        self.btn_pasar.setText(_translate("sala", "Pasar"))
        self.btn_Allin.setText(_translate("sala", "All in"))
        self.btn_retirarse.setText(_translate("sala", "Retirarse"))
        self.btn_subir.setText(_translate("sala", "Subir"))

import fondo_carta_rc
import mazo_rc
import mesa_poquer_rc
